name: Gosec SARIF Scan

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  security-scan:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Install gosec v2.18.2
      run: |
        go install github.com/securego/gosec/v2/cmd/gosec@v2.18.2
        echo "$GOPATH/bin" >> $GITHUB_PATH

    - name: Run gosec scan (SARIF output)
      run: |
        gosec -fmt sarif -out gosec-results.sarif ./...
        echo "SARIF written to gosec-results.sarif"
      continue-on-error: true

    - name: Upload SARIF to GitHub (optional, for Code Scanning UI)
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: gosec-results.sarif
