name: Gosec new Scan

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  security-scan:
    runs-on: ubuntu-latest
    
    steps:
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21.6'

    - name: Install gosec v2.18.2
      run: |
        run: |
        go install github.com/securego/gosec/v2/cmd/gosec@v2.18.2
        echo "$GOPATH/bin" >> $GITHUB_PATH

    - name: Run gosec scan (SARIF output)
      run: |
        gosec -no-fail -verbose -fmt sarif -out results.sarif ./...
        echo "SARIF written to results.sarif"
      
    
    - name: Upload SARIF file
      uses: github/codeql-action/upload-sarif@v3
      with:
          # Path to SARIF file relative to the root of the repository
          sarif_file: results.sarif
    - name: Upload Report
      uses: actions/upload-artifact@v4
      with:
          name: GoSec report
          path: |
            results.sarif
